### ISSUE TITLE
Tests should fail when broker is not running

### ISSUE THREAD

**Issue by scholzj** [Eurex-Clearing-Messaging-Interfaces/Python-Code-Examples#4]
When CircleCI/Travis fails to download the docker image, the tests should fail. However, it looks like some of the tests start looping instead:
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused
ERROR:root:proton:io: recv: Connection refused

See more details in https://circleci.com/gh/Eurex-Clearing-Messaging-Interfaces/Python-Code-Examples/21

**Comment by scholzj** [comment]
@zerola Can we close this?

**Comment by zerola** [comment]
Yes, I am closing the issue.
